# Site settings
title: Delivery Bot Pitch
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #0B3C5D
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Build settings
markdown: kramdown
permalink: pretty
